/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_hyphenate_javawrapper_channel_EMChannel */

#ifndef _Included_com_hyphenate_javawrapper_channel_EMChannel
#define _Included_com_hyphenate_javawrapper_channel_EMChannel
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_hyphenate_javawrapper_channel_EMChannel
 * Method:    callListener
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_hyphenate_javawrapper_channel_EMChannel_callListener
  (JNIEnv *, jobject, jstring, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
