/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_hyphenate_javawrapper_JavaWrapper */

#ifndef _Included_com_hyphenate_javawrapper_JavaWrapper
#define _Included_com_hyphenate_javawrapper_JavaWrapper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_hyphenate_javawrapper_JavaWrapper
 * Method:    callListener
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_hyphenate_javawrapper_JavaWrapper_callListener
  (JNIEnv *, jobject, jstring, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
