/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_hyphenate_cwrapper_EMCWrapperListener */

#ifndef _Included_com_hyphenate_cwrapper_EMCWrapperListener
#define _Included_com_hyphenate_cwrapper_EMCWrapperListener
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_hyphenate_cwrapper_EMCWrapperListener
 * Method:    onReceive
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_hyphenate_cwrapper_EMCWrapperListener_onReceive
  (JNIEnv *, jobject, jstring, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
